#include "BarriEww/Vulkan/VulkanHostImagePresentationResources.hpp"

#include <algorithm>
#include <cassert>
#include <iterator>
#include <limits>
#include <utility>

#include "BarriEww/Vulkan/Shaders/HostImagePresentationFragmentShader.hpp"
#include "BarriEww/Vulkan/Shaders/HostImagePresentationVertexShader.hpp"

namespace barrieww {

namespace {

constexpr VkImageSubresourceRange g_colorSubresourceRange{
    VK_IMAGE_ASPECT_COLOR_BIT, 0u, 1u, 0u, 1u};

/**
 * @note ThreadSafety: Render-thread confined through the calling creation operation.
 * @brief Wraps one exact Vulkan creation failure without remapping.
 * @param VkResult vulkanResult Raw Vulkan result returned by the failed operation
 * @return VulkanHostImagePresentationResources::CreationFailure Wrapped result
 * @warning MemoryOwnership: Returns a value containing no owned memory or Vulkan object.
 */
VulkanHostImagePresentationResources::CreationFailure creationFailure(
    VkResult vulkanResult) noexcept {
    return {vulkanResult};
}

/**
 * @note ThreadSafety: Render-thread confined and read-only over caller-owned input.
 * @brief Validates every borrowed handle and fixed matrix dimension before Vulkan calls.
 * @param const VulkanHostImagePresentationResources::CreateInfo& createInfo Candidate input
 * @return bool True when creation can safely traverse and materialize the matrix
 * @warning MemoryOwnership: Borrows every handle and span and does not extend lifetimes.
 */
bool isValidCreateInfo(
    const VulkanHostImagePresentationResources::CreateInfo& createInfo) noexcept {
    if (createInfo.logicalDevice == VK_NULL_HANDLE
        || createInfo.hostImage == VK_NULL_HANDLE
        || createInfo.hostImageFormat == VK_FORMAT_UNDEFINED
        || createInfo.swapchainImageFormat == VK_FORMAT_UNDEFINED
        || createInfo.extent.width == 0u || createInfo.extent.height == 0u
        || createInfo.frameSlotCount == 0u || createInfo.swapchainImages.empty()
        || createInfo.swapchainImages.size() != createInfo.swapchainImageViews.size()) {
        return false;
    }
    if (createInfo.swapchainImages.size()
        > std::numeric_limits<std::size_t>::max() / createInfo.frameSlotCount) {
        return false;
    }
    const std::size_t commandBufferCount =
        createInfo.swapchainImages.size() * createInfo.frameSlotCount;
    if (commandBufferCount > std::numeric_limits<std::uint32_t>::max()) {
        return false;
    }
    return std::ranges::none_of(createInfo.swapchainImages,
                                [](VkImage image) { return image == VK_NULL_HANDLE; })
        && std::ranges::none_of(
            createInfo.swapchainImageViews,
            [](VkImageView imageView) { return imageView == VK_NULL_HANDLE; });
}

/**
 * @note ThreadSafety: Render-thread confined through the calling creation operation.
 * @brief Creates one shader module from an aligned build-generated byte array.
 * @param VkDevice logicalDevice Borrowed logical device
 * @param const std::array<std::byte, binaryByteCount>& shaderBinary Embedded shader bytes
 * @param VkShaderModule& shaderModule Receives the created shader module
 * @return VkResult Exact Vulkan creation result
 * @warning MemoryOwnership: On success transfers the shader-module handle to the caller;
 *          the logical device and embedded shader bytes remain borrowed.
 */
template<std::size_t binaryByteCount>
VkResult createShaderModule(
    VkDevice logicalDevice,
    const std::array<std::byte, binaryByteCount>& shaderBinary,
    VkShaderModule& shaderModule) noexcept {
    const VkShaderModuleCreateInfo createInfo{
        VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
        nullptr,
        0u,
        shaderBinary.size(),
        reinterpret_cast<const std::uint32_t*>(shaderBinary.data()),
    };
    return vkCreateShaderModule(logicalDevice, &createInfo, nullptr, &shaderModule);
}

} // namespace

std::expected<VulkanHostImagePresentationResources,
              VulkanHostImagePresentationResources::CreationFailure>
VulkanHostImagePresentationResources::create(const CreateInfo& createInfo) {
    if (!isValidCreateInfo(createInfo)) {
        return std::unexpected(creationFailure(VK_ERROR_INITIALIZATION_FAILED));
    }

    VulkanHostImagePresentationResources resources;
    resources.m_logicalDevice = createInfo.logicalDevice;
    resources.m_swapchainImageCount = createInfo.swapchainImages.size();

    const VkImageViewCreateInfo imageViewCreateInfo{
        VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO,
        nullptr,
        0u,
        createInfo.hostImage,
        VK_IMAGE_VIEW_TYPE_2D,
        createInfo.hostImageFormat,
        VkComponentMapping{VK_COMPONENT_SWIZZLE_IDENTITY, VK_COMPONENT_SWIZZLE_IDENTITY,
                           VK_COMPONENT_SWIZZLE_IDENTITY, VK_COMPONENT_SWIZZLE_IDENTITY},
        g_colorSubresourceRange,
    };
    VkResult vulkanResult = vkCreateImageView(createInfo.logicalDevice,
                                              &imageViewCreateInfo, nullptr,
                                              &resources.m_hostImageView);
    if (vulkanResult != VK_SUCCESS) {
        return std::unexpected(creationFailure(vulkanResult));
    }

    const VkSamplerCreateInfo samplerCreateInfo{
        VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO,
        nullptr,
        0u,
        VK_FILTER_NEAREST,
        VK_FILTER_NEAREST,
        VK_SAMPLER_MIPMAP_MODE_NEAREST,
        VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE,
        VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE,
        VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE,
        0.0f,
        VK_FALSE,
        1.0f,
        VK_FALSE,
        VK_COMPARE_OP_ALWAYS,
        0.0f,
        0.0f,
        VK_BORDER_COLOR_FLOAT_TRANSPARENT_BLACK,
        VK_FALSE,
    };
    vulkanResult = vkCreateSampler(createInfo.logicalDevice, &samplerCreateInfo,
                                   nullptr, &resources.m_sampler);
    if (vulkanResult != VK_SUCCESS) {
        return std::unexpected(creationFailure(vulkanResult));
    }

    const VkDescriptorSetLayoutBinding descriptorBinding{
        0u,
        VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
        1u,
        VK_SHADER_STAGE_FRAGMENT_BIT,
        nullptr,
    };
    const VkDescriptorSetLayoutCreateInfo descriptorSetLayoutCreateInfo{
        VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
        nullptr,
        0u,
        1u,
        &descriptorBinding,
    };
    vulkanResult = vkCreateDescriptorSetLayout(
        createInfo.logicalDevice, &descriptorSetLayoutCreateInfo, nullptr,
        &resources.m_descriptorSetLayout);
    if (vulkanResult != VK_SUCCESS) {
        return std::unexpected(creationFailure(vulkanResult));
    }

    const VkDescriptorPoolSize descriptorPoolSize{
        VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 1u};
    const VkDescriptorPoolCreateInfo descriptorPoolCreateInfo{
        VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO,
        nullptr,
        0u,
        1u,
        1u,
        &descriptorPoolSize,
    };
    vulkanResult = vkCreateDescriptorPool(createInfo.logicalDevice,
                                          &descriptorPoolCreateInfo, nullptr,
                                          &resources.m_descriptorPool);
    if (vulkanResult != VK_SUCCESS) {
        return std::unexpected(creationFailure(vulkanResult));
    }

    const VkDescriptorSetAllocateInfo descriptorSetAllocateInfo{
        VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO,
        nullptr,
        resources.m_descriptorPool,
        1u,
        &resources.m_descriptorSetLayout,
    };
    vulkanResult = vkAllocateDescriptorSets(createInfo.logicalDevice,
                                            &descriptorSetAllocateInfo,
                                            &resources.m_descriptorSet);
    if (vulkanResult != VK_SUCCESS) {
        return std::unexpected(creationFailure(vulkanResult));
    }
    const VkDescriptorImageInfo descriptorImageInfo{
        resources.m_sampler,
        resources.m_hostImageView,
        VK_IMAGE_LAYOUT_GENERAL,
    };
    const VkWriteDescriptorSet descriptorWrite{
        VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
        nullptr,
        resources.m_descriptorSet,
        0u,
        0u,
        1u,
        VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
        &descriptorImageInfo,
        nullptr,
        nullptr,
    };
    vkUpdateDescriptorSets(createInfo.logicalDevice, 1u, &descriptorWrite, 0u, nullptr);

    const VkPipelineLayoutCreateInfo pipelineLayoutCreateInfo{
        VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
        nullptr,
        0u,
        1u,
        &resources.m_descriptorSetLayout,
        0u,
        nullptr,
    };
    vulkanResult = vkCreatePipelineLayout(createInfo.logicalDevice,
                                          &pipelineLayoutCreateInfo, nullptr,
                                          &resources.m_pipelineLayout);
    if (vulkanResult != VK_SUCCESS) {
        return std::unexpected(creationFailure(vulkanResult));
    }

    VkShaderModule vertexShaderModule = VK_NULL_HANDLE;
    vulkanResult = createShaderModule(
        createInfo.logicalDevice,
        vulkan::shaders::g_hostImagePresentationVertexShaderBinary,
        vertexShaderModule);
    if (vulkanResult != VK_SUCCESS) {
        return std::unexpected(creationFailure(vulkanResult));
    }
    VkShaderModule fragmentShaderModule = VK_NULL_HANDLE;
    vulkanResult = createShaderModule(
        createInfo.logicalDevice,
        vulkan::shaders::g_hostImagePresentationFragmentShaderBinary,
        fragmentShaderModule);
    if (vulkanResult != VK_SUCCESS) {
        vkDestroyShaderModule(createInfo.logicalDevice, vertexShaderModule, nullptr);
        return std::unexpected(creationFailure(vulkanResult));
    }

    const std::array shaderStages{
        VkPipelineShaderStageCreateInfo{VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
                                        nullptr, 0u, VK_SHADER_STAGE_VERTEX_BIT,
                                        vertexShaderModule, "main", nullptr},
        VkPipelineShaderStageCreateInfo{VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
                                        nullptr, 0u, VK_SHADER_STAGE_FRAGMENT_BIT,
                                        fragmentShaderModule, "main", nullptr},
    };
    const VkPipelineVertexInputStateCreateInfo vertexInputState{
        VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO,
        nullptr, 0u, 0u, nullptr, 0u, nullptr};
    const VkPipelineInputAssemblyStateCreateInfo inputAssemblyState{
        VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO,
        nullptr, 0u, VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST, VK_FALSE};
    const VkViewport viewport{0.0f, 0.0f,
                              static_cast<float>(createInfo.extent.width),
                              static_cast<float>(createInfo.extent.height),
                              0.0f, 1.0f};
    const VkRect2D scissor{{0, 0}, createInfo.extent};
    const VkPipelineViewportStateCreateInfo viewportState{
        VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO,
        nullptr, 0u, 1u, &viewport, 1u, &scissor};
    const VkPipelineRasterizationStateCreateInfo rasterizationState{
        VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO,
        nullptr, 0u, VK_FALSE, VK_FALSE, VK_POLYGON_MODE_FILL, VK_CULL_MODE_NONE,
        VK_FRONT_FACE_COUNTER_CLOCKWISE, VK_FALSE, 0.0f, 0.0f, 0.0f, 1.0f};
    const VkPipelineMultisampleStateCreateInfo multisampleState{
        VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO,
        nullptr, 0u, VK_SAMPLE_COUNT_1_BIT, VK_FALSE, 1.0f, nullptr, VK_FALSE, VK_FALSE};
    const VkPipelineColorBlendAttachmentState colorBlendAttachment{
        VK_FALSE,
        VK_BLEND_FACTOR_ONE,
        VK_BLEND_FACTOR_ZERO,
        VK_BLEND_OP_ADD,
        VK_BLEND_FACTOR_ONE,
        VK_BLEND_FACTOR_ZERO,
        VK_BLEND_OP_ADD,
        VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT
            | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT,
    };
    const VkPipelineColorBlendStateCreateInfo colorBlendState{
        VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO,
        nullptr, 0u, VK_FALSE, VK_LOGIC_OP_COPY, 1u, &colorBlendAttachment, {0, 0, 0, 0}};
    const VkPipelineRenderingCreateInfo renderingCreateInfo{
        VK_STRUCTURE_TYPE_PIPELINE_RENDERING_CREATE_INFO,
        nullptr, 0u, 1u, &createInfo.swapchainImageFormat,
        VK_FORMAT_UNDEFINED, VK_FORMAT_UNDEFINED};
    const VkGraphicsPipelineCreateInfo graphicsPipelineCreateInfo{
        VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO,
        &renderingCreateInfo,
        0u,
        static_cast<std::uint32_t>(shaderStages.size()),
        shaderStages.data(),
        &vertexInputState,
        &inputAssemblyState,
        nullptr,
        &viewportState,
        &rasterizationState,
        &multisampleState,
        nullptr,
        &colorBlendState,
        nullptr,
        resources.m_pipelineLayout,
        VK_NULL_HANDLE,
        0u,
        VK_NULL_HANDLE,
        -1,
    };
    vulkanResult = vkCreateGraphicsPipelines(
        createInfo.logicalDevice, VK_NULL_HANDLE, 1u,
        &graphicsPipelineCreateInfo, nullptr, &resources.m_pipeline);
    vkDestroyShaderModule(createInfo.logicalDevice, fragmentShaderModule, nullptr);
    vkDestroyShaderModule(createInfo.logicalDevice, vertexShaderModule, nullptr);
    if (vulkanResult != VK_SUCCESS) {
        return std::unexpected(creationFailure(vulkanResult));
    }

    const VkCommandPoolCreateInfo commandPoolCreateInfo{
        VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO,
        nullptr,
        0u,
        createInfo.graphicsQueueFamilyIndex,
    };
    vulkanResult = vkCreateCommandPool(createInfo.logicalDevice,
                                       &commandPoolCreateInfo, nullptr,
                                       &resources.m_commandPool);
    if (vulkanResult != VK_SUCCESS) {
        return std::unexpected(creationFailure(vulkanResult));
    }
    const std::size_t commandBufferCount =
        createInfo.frameSlotCount * createInfo.swapchainImages.size();
    resources.m_commandBuffers.resize(commandBufferCount);
    const VkCommandBufferAllocateInfo commandBufferAllocateInfo{
        VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO,
        nullptr,
        resources.m_commandPool,
        VK_COMMAND_BUFFER_LEVEL_PRIMARY,
        static_cast<std::uint32_t>(commandBufferCount),
    };
    vulkanResult = vkAllocateCommandBuffers(createInfo.logicalDevice,
                                            &commandBufferAllocateInfo,
                                            resources.m_commandBuffers.data());
    if (vulkanResult != VK_SUCCESS) {
        return std::unexpected(creationFailure(vulkanResult));
    }

    /**
     * @note ThreadSafety: Creation is render-thread confined and no command buffer is
     *       externally visible until the complete matrix has been recorded.
     * @brief Records a fixed row-major command matrix. Each frame slot owns one row and
     *        each swapchain image owns one column, so matrixIndex equals
     *        frameSlotIndex * swapchainImageCount + imageIndex. The host image remains in
     *        GENERAL and is made visible to fragment sampling; the selected swapchain image
     *        is fully overwritten by dynamic rendering and then prepared for presentation.
     *
     * Invariants and assumptions:
     * - hostImage remains GENERAL and its producer submission precedes this command buffer;
     * - host and swapchain extents are exact, positive, and fixed for the generation;
     * - borrowed images and image views outlive every recorded command buffer;
     * - dynamic rendering is enabled and every swapchain image supports color attachment;
     * - full overwrite permits discarding prior swapchain contents with UNDEFINED.
     *
     * Semantic pseudocode:
     * for each frameSlotIndex in frameSlotCount:
     *     for each imageIndex in swapchainImageCount:
     *         matrixIndex = frameSlotIndex * swapchainImageCount + imageIndex
     *         begin commandBuffers[matrixIndex]
     *         barrier hostImage GENERAL -> GENERAL from
     *             COLOR_ATTACHMENT_OUTPUT | TRANSFER and MEMORY_WRITE to
     *             FRAGMENT_SHADER and SHADER_READ
     *         barrier swapchainImages[imageIndex] UNDEFINED -> COLOR_ATTACHMENT_OPTIMAL
     *         begin dynamic rendering with DONT_CARE load and STORE output
     *         bind pipeline and descriptor set zero; draw three vertices
     *         end dynamic rendering
     *         barrier swapchainImages[imageIndex]
     *             COLOR_ATTACHMENT_OPTIMAL -> PRESENT_SRC_KHR
     *         end commandBuffers[matrixIndex]
     *
     * Creation complexity is O(frameSlotCount * swapchainImageCount) time and storage.
     * commandBuffer lookup is O(1) time with no allocation or recording.
     */
    for (std::uint32_t frameSlotIndex = 0u;
         frameSlotIndex < createInfo.frameSlotCount; ++frameSlotIndex) {
        for (std::size_t imageIndex = 0u;
             imageIndex < createInfo.swapchainImages.size(); ++imageIndex) {
            const std::size_t matrixIndex =
                frameSlotIndex * createInfo.swapchainImages.size() + imageIndex;
            const VkCommandBuffer commandBuffer = resources.m_commandBuffers[matrixIndex];
            const VkCommandBufferBeginInfo beginInfo{
                VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO,
                nullptr,
                0u,
                nullptr,
            };
            vulkanResult = vkBeginCommandBuffer(commandBuffer, &beginInfo);
            if (vulkanResult != VK_SUCCESS) {
                return std::unexpected(creationFailure(vulkanResult));
            }

            const VkImageMemoryBarrier hostImageBarrier{
                VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER,
                nullptr,
                VK_ACCESS_MEMORY_WRITE_BIT,
                VK_ACCESS_SHADER_READ_BIT,
                VK_IMAGE_LAYOUT_GENERAL,
                VK_IMAGE_LAYOUT_GENERAL,
                VK_QUEUE_FAMILY_IGNORED,
                VK_QUEUE_FAMILY_IGNORED,
                createInfo.hostImage,
                g_colorSubresourceRange,
            };
            vkCmdPipelineBarrier(
                commandBuffer,
                VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT
                    | VK_PIPELINE_STAGE_TRANSFER_BIT,
                VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT, 0u, 0u, nullptr, 0u, nullptr,
                1u, &hostImageBarrier);

            const VkImageMemoryBarrier colorAttachmentBarrier{
                VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER,
                nullptr,
                0u,
                VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT,
                VK_IMAGE_LAYOUT_UNDEFINED,
                VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
                VK_QUEUE_FAMILY_IGNORED,
                VK_QUEUE_FAMILY_IGNORED,
                createInfo.swapchainImages[imageIndex],
                g_colorSubresourceRange,
            };
            vkCmdPipelineBarrier(commandBuffer, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
                                 VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
                                 0u, 0u, nullptr, 0u, nullptr, 1u,
                                 &colorAttachmentBarrier);

            const VkRenderingAttachmentInfo colorAttachment{
                VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO,
                nullptr,
                createInfo.swapchainImageViews[imageIndex],
                VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
                VK_RESOLVE_MODE_NONE,
                VK_NULL_HANDLE,
                VK_IMAGE_LAYOUT_UNDEFINED,
                VK_ATTACHMENT_LOAD_OP_DONT_CARE,
                VK_ATTACHMENT_STORE_OP_STORE,
                {},
            };
            const VkRenderingInfo renderingInfo{
                VK_STRUCTURE_TYPE_RENDERING_INFO,
                nullptr,
                0u,
                VkRect2D{{0, 0}, createInfo.extent},
                1u,
                0u,
                1u,
                &colorAttachment,
                nullptr,
                nullptr,
            };
            vkCmdBeginRenderingKHR(commandBuffer, &renderingInfo);
            vkCmdBindPipeline(commandBuffer, VK_PIPELINE_BIND_POINT_GRAPHICS,
                              resources.m_pipeline);
            vkCmdBindDescriptorSets(commandBuffer, VK_PIPELINE_BIND_POINT_GRAPHICS,
                                    resources.m_pipelineLayout, 0u, 1u,
                                    &resources.m_descriptorSet, 0u, nullptr);
            vkCmdDraw(commandBuffer, 3u, 1u, 0u, 0u);
            vkCmdEndRenderingKHR(commandBuffer);

            const VkImageMemoryBarrier presentBarrier{
                VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER,
                nullptr,
                VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT,
                0u,
                VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
                VK_IMAGE_LAYOUT_PRESENT_SRC_KHR,
                VK_QUEUE_FAMILY_IGNORED,
                VK_QUEUE_FAMILY_IGNORED,
                createInfo.swapchainImages[imageIndex],
                g_colorSubresourceRange,
            };
            vkCmdPipelineBarrier(commandBuffer,
                                 VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
                                 VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT,
                                 0u, 0u, nullptr, 0u, nullptr, 1u, &presentBarrier);
            vulkanResult = vkEndCommandBuffer(commandBuffer);
            if (vulkanResult != VK_SUCCESS) {
                return std::unexpected(creationFailure(vulkanResult));
            }
        }
    }

    return resources;
}

VulkanHostImagePresentationResources::VulkanHostImagePresentationResources(
    VulkanHostImagePresentationResources&& movedFrom) noexcept
    : m_logicalDevice(std::exchange(movedFrom.m_logicalDevice, VK_NULL_HANDLE)),
      m_hostImageView(std::exchange(movedFrom.m_hostImageView, VK_NULL_HANDLE)),
      m_sampler(std::exchange(movedFrom.m_sampler, VK_NULL_HANDLE)),
      m_descriptorSetLayout(
          std::exchange(movedFrom.m_descriptorSetLayout, VK_NULL_HANDLE)),
      m_descriptorPool(std::exchange(movedFrom.m_descriptorPool, VK_NULL_HANDLE)),
      m_descriptorSet(std::exchange(movedFrom.m_descriptorSet, VK_NULL_HANDLE)),
      m_pipelineLayout(std::exchange(movedFrom.m_pipelineLayout, VK_NULL_HANDLE)),
      m_pipeline(std::exchange(movedFrom.m_pipeline, VK_NULL_HANDLE)),
      m_commandPool(std::exchange(movedFrom.m_commandPool, VK_NULL_HANDLE)),
      m_commandBuffers(std::move(movedFrom.m_commandBuffers)),
      m_swapchainImageCount(std::exchange(movedFrom.m_swapchainImageCount, 0u)) {}

VulkanHostImagePresentationResources::~VulkanHostImagePresentationResources() {
    destroyOwnedObjects();
}

VkCommandBuffer VulkanHostImagePresentationResources::commandBuffer(
    std::uint32_t frameSlotIndex, std::uint32_t imageIndex) const noexcept {
    assert(m_swapchainImageCount != 0u);
    assert(imageIndex < m_swapchainImageCount);
    const std::size_t matrixIndex = frameSlotIndex * m_swapchainImageCount + imageIndex;
    assert(matrixIndex < m_commandBuffers.size());
    return m_commandBuffers[matrixIndex];
}

std::expected<void, VkResult>
VulkanHostImagePresentationResources::destroyAfterSubmittedFrames(
    std::span<const VkFence> submittedFrameFences,
    VkFence unsubmittedOpenFrameFence) {
    if (m_logicalDevice == VK_NULL_HANDLE) {
        return {};
    }
    std::vector<VkFence> fencesToWait;
    fencesToWait.reserve(submittedFrameFences.size());
    std::ranges::copy_if(
        submittedFrameFences, std::back_inserter(fencesToWait),
        [unsubmittedOpenFrameFence](VkFence fence) {
            return fence != VK_NULL_HANDLE && fence != unsubmittedOpenFrameFence;
        });
    if (!fencesToWait.empty()) {
        const VkResult vulkanResult = vkWaitForFences(
            m_logicalDevice, static_cast<std::uint32_t>(fencesToWait.size()),
            fencesToWait.data(), VK_TRUE, std::numeric_limits<std::uint64_t>::max());
        if (vulkanResult != VK_SUCCESS) {
            return std::unexpected(vulkanResult);
        }
    }
    destroyOwnedObjects();
    return {};
}

void VulkanHostImagePresentationResources::destroyOwnedObjects() noexcept {
    if (m_logicalDevice == VK_NULL_HANDLE) {
        return;
    }
    if (m_commandPool != VK_NULL_HANDLE) {
        vkDestroyCommandPool(m_logicalDevice, m_commandPool, nullptr);
    }
    if (m_pipeline != VK_NULL_HANDLE) {
        vkDestroyPipeline(m_logicalDevice, m_pipeline, nullptr);
    }
    if (m_pipelineLayout != VK_NULL_HANDLE) {
        vkDestroyPipelineLayout(m_logicalDevice, m_pipelineLayout, nullptr);
    }
    if (m_descriptorPool != VK_NULL_HANDLE) {
        vkDestroyDescriptorPool(m_logicalDevice, m_descriptorPool, nullptr);
    }
    if (m_descriptorSetLayout != VK_NULL_HANDLE) {
        vkDestroyDescriptorSetLayout(m_logicalDevice, m_descriptorSetLayout, nullptr);
    }
    if (m_sampler != VK_NULL_HANDLE) {
        vkDestroySampler(m_logicalDevice, m_sampler, nullptr);
    }
    if (m_hostImageView != VK_NULL_HANDLE) {
        vkDestroyImageView(m_logicalDevice, m_hostImageView, nullptr);
    }
    m_commandBuffers.clear();
    m_commandPool = VK_NULL_HANDLE;
    m_pipeline = VK_NULL_HANDLE;
    m_pipelineLayout = VK_NULL_HANDLE;
    m_descriptorSet = VK_NULL_HANDLE;
    m_descriptorPool = VK_NULL_HANDLE;
    m_descriptorSetLayout = VK_NULL_HANDLE;
    m_sampler = VK_NULL_HANDLE;
    m_hostImageView = VK_NULL_HANDLE;
    m_swapchainImageCount = 0u;
    m_logicalDevice = VK_NULL_HANDLE;
}

} // namespace barrieww
