#include "BarriEww/Vulkan/VulkanHostImageCompositionResources.hpp"

#include <array>
#include <cstddef>
#include <cstdint>
#include <utility>

#include "BarriEww/Vulkan/Shaders/HostImagePresentationFragmentShader.hpp"
#include "BarriEww/Vulkan/Shaders/HostImagePresentationVertexShader.hpp"

namespace barrieww {

namespace {

constexpr VkImageSubresourceRange g_colorSubresourceRange{VK_IMAGE_ASPECT_COLOR_BIT, 0u, 1u, 0u,
                                                          1u};

/**
 * @note ThreadSafety: Render-thread confined through composition creation.
 * @brief Creates one shader module from an aligned build-generated byte array.
 * @param VkDevice logicalDevice Borrowed logical device
 * @param const std::array<std::byte, binaryByteCount>& shaderBinary Embedded
 * shader bytes
 * @param VkShaderModule& shaderModule Receives the created shader module
 * @return VkResult Exact Vulkan creation result
 * @warning MemoryOwnership: Success transfers shaderModule ownership to the
 * caller; all input storage and the logical device remain borrowed.
 */
template <std::size_t binaryByteCount>
VkResult createShaderModule(VkDevice logicalDevice,
                            const std::array<std::byte, binaryByteCount>& shaderBinary,
                            VkShaderModule& shaderModule) noexcept {
    const VkShaderModuleCreateInfo createInfo{
        VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO, nullptr, 0u, shaderBinary.size(),
        reinterpret_cast<const std::uint32_t*>(shaderBinary.data())};
    return vkCreateShaderModule(logicalDevice, &createInfo, nullptr, &shaderModule);
}

} // namespace

std::expected<VulkanHostImageCompositionResources, VkResult>
VulkanHostImageCompositionResources::create(const CreateInfo& createInfo) {
    if (createInfo.logicalDevice == VK_NULL_HANDLE || createInfo.hostImage == VK_NULL_HANDLE ||
        createInfo.hostImageFormat == VK_FORMAT_UNDEFINED ||
        createInfo.outputImageFormat == VK_FORMAT_UNDEFINED || createInfo.extent.width == 0u ||
        createInfo.extent.height == 0u) {
        return std::unexpected(VK_ERROR_INITIALIZATION_FAILED);
    }

    VulkanHostImageCompositionResources resources;
    resources.m_logicalDevice = createInfo.logicalDevice;
    resources.m_extent = createInfo.extent;
    resources.m_beginRenderingFunction = reinterpret_cast<PFN_vkCmdBeginRenderingKHR>(
        vkGetDeviceProcAddr(createInfo.logicalDevice, "vkCmdBeginRenderingKHR"));
    resources.m_endRenderingFunction = reinterpret_cast<PFN_vkCmdEndRenderingKHR>(
        vkGetDeviceProcAddr(createInfo.logicalDevice, "vkCmdEndRenderingKHR"));
    if (resources.m_beginRenderingFunction == nullptr ||
        resources.m_endRenderingFunction == nullptr) {
        return std::unexpected(VK_ERROR_EXTENSION_NOT_PRESENT);
    }

    const VkImageViewCreateInfo imageViewCreateInfo{
        VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO,
        nullptr,
        0u,
        createInfo.hostImage,
        VK_IMAGE_VIEW_TYPE_2D,
        createInfo.hostImageFormat,
        VkComponentMapping{VK_COMPONENT_SWIZZLE_IDENTITY, VK_COMPONENT_SWIZZLE_IDENTITY,
                           VK_COMPONENT_SWIZZLE_IDENTITY, VK_COMPONENT_SWIZZLE_IDENTITY},
        g_colorSubresourceRange};
    VkResult vulkanResult = vkCreateImageView(createInfo.logicalDevice, &imageViewCreateInfo,
                                              nullptr, &resources.m_hostImageView);
    if (vulkanResult != VK_SUCCESS) {
        return std::unexpected(vulkanResult);
    }

    const VkSamplerCreateInfo samplerCreateInfo{VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO,
                                                nullptr,
                                                0u,
                                                VK_FILTER_NEAREST,
                                                VK_FILTER_NEAREST,
                                                VK_SAMPLER_MIPMAP_MODE_NEAREST,
                                                VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE,
                                                VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE,
                                                VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE,
                                                0.0f,
                                                VK_FALSE,
                                                1.0f,
                                                VK_FALSE,
                                                VK_COMPARE_OP_ALWAYS,
                                                0.0f,
                                                0.0f,
                                                VK_BORDER_COLOR_FLOAT_TRANSPARENT_BLACK,
                                                VK_FALSE};
    vulkanResult = vkCreateSampler(createInfo.logicalDevice, &samplerCreateInfo, nullptr,
                                   &resources.m_sampler);
    if (vulkanResult != VK_SUCCESS) {
        return std::unexpected(vulkanResult);
    }

    const VkDescriptorSetLayoutBinding descriptorBinding{
        0u, VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 1u, VK_SHADER_STAGE_FRAGMENT_BIT, nullptr};
    const VkDescriptorSetLayoutCreateInfo descriptorSetLayoutCreateInfo{
        VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO, nullptr, 0u, 1u, &descriptorBinding};
    vulkanResult =
        vkCreateDescriptorSetLayout(createInfo.logicalDevice, &descriptorSetLayoutCreateInfo,
                                    nullptr, &resources.m_descriptorSetLayout);
    if (vulkanResult != VK_SUCCESS) {
        return std::unexpected(vulkanResult);
    }

    const VkDescriptorPoolSize descriptorPoolSize{VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 1u};
    const VkDescriptorPoolCreateInfo descriptorPoolCreateInfo{
        VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO, nullptr, 0u, 1u, 1u, &descriptorPoolSize};
    vulkanResult = vkCreateDescriptorPool(createInfo.logicalDevice, &descriptorPoolCreateInfo,
                                          nullptr, &resources.m_descriptorPool);
    if (vulkanResult != VK_SUCCESS) {
        return std::unexpected(vulkanResult);
    }

    const VkDescriptorSetAllocateInfo descriptorSetAllocateInfo{
        VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO, nullptr, resources.m_descriptorPool, 1u,
        &resources.m_descriptorSetLayout};
    vulkanResult = vkAllocateDescriptorSets(createInfo.logicalDevice, &descriptorSetAllocateInfo,
                                            &resources.m_descriptorSet);
    if (vulkanResult != VK_SUCCESS) {
        return std::unexpected(vulkanResult);
    }
    const VkDescriptorImageInfo descriptorImageInfo{resources.m_sampler, resources.m_hostImageView,
                                                    VK_IMAGE_LAYOUT_GENERAL};
    const VkWriteDescriptorSet descriptorWrite{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
                                               nullptr,
                                               resources.m_descriptorSet,
                                               0u,
                                               0u,
                                               1u,
                                               VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
                                               &descriptorImageInfo,
                                               nullptr,
                                               nullptr};
    vkUpdateDescriptorSets(createInfo.logicalDevice, 1u, &descriptorWrite, 0u, nullptr);

    const VkPipelineLayoutCreateInfo pipelineLayoutCreateInfo{
        VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
        nullptr,
        0u,
        1u,
        &resources.m_descriptorSetLayout,
        0u,
        nullptr};
    vulkanResult = vkCreatePipelineLayout(createInfo.logicalDevice, &pipelineLayoutCreateInfo,
                                          nullptr, &resources.m_pipelineLayout);
    if (vulkanResult != VK_SUCCESS) {
        return std::unexpected(vulkanResult);
    }

    VkShaderModule vertexShaderModule = VK_NULL_HANDLE;
    vulkanResult = createShaderModule(createInfo.logicalDevice,
                                      vulkan::shaders::g_hostImagePresentationVertexShaderBinary,
                                      vertexShaderModule);
    if (vulkanResult != VK_SUCCESS) {
        return std::unexpected(vulkanResult);
    }
    VkShaderModule fragmentShaderModule = VK_NULL_HANDLE;
    vulkanResult = createShaderModule(createInfo.logicalDevice,
                                      vulkan::shaders::g_hostImagePresentationFragmentShaderBinary,
                                      fragmentShaderModule);
    if (vulkanResult != VK_SUCCESS) {
        vkDestroyShaderModule(createInfo.logicalDevice, vertexShaderModule, nullptr);
        return std::unexpected(vulkanResult);
    }

    const std::array shaderStages{
        VkPipelineShaderStageCreateInfo{VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
                                        nullptr, 0u, VK_SHADER_STAGE_VERTEX_BIT, vertexShaderModule,
                                        "main", nullptr},
        VkPipelineShaderStageCreateInfo{VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
                                        nullptr, 0u, VK_SHADER_STAGE_FRAGMENT_BIT,
                                        fragmentShaderModule, "main", nullptr}};
    const VkPipelineVertexInputStateCreateInfo vertexInputState{
        VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO,
        nullptr,
        0u,
        0u,
        nullptr,
        0u,
        nullptr};
    const VkPipelineInputAssemblyStateCreateInfo inputAssemblyState{
        VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO, nullptr, 0u,
        VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST, VK_FALSE};
    const VkViewport viewport{0.0f,
                              0.0f,
                              static_cast<float>(createInfo.extent.width),
                              static_cast<float>(createInfo.extent.height),
                              0.0f,
                              1.0f};
    const VkRect2D scissor{{0, 0}, createInfo.extent};
    const VkPipelineViewportStateCreateInfo viewportState{
        VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO,
        nullptr,
        0u,
        1u,
        &viewport,
        1u,
        &scissor};
    const VkPipelineRasterizationStateCreateInfo rasterizationState{
        VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO,
        nullptr,
        0u,
        VK_FALSE,
        VK_FALSE,
        VK_POLYGON_MODE_FILL,
        VK_CULL_MODE_NONE,
        VK_FRONT_FACE_COUNTER_CLOCKWISE,
        VK_FALSE,
        0.0f,
        0.0f,
        0.0f,
        1.0f};
    const VkPipelineMultisampleStateCreateInfo multisampleState{
        VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO,
        nullptr,
        0u,
        VK_SAMPLE_COUNT_1_BIT,
        VK_FALSE,
        1.0f,
        nullptr,
        VK_FALSE,
        VK_FALSE};
    const VkPipelineColorBlendAttachmentState colorBlendAttachment{
        VK_FALSE,
        VK_BLEND_FACTOR_ONE,
        VK_BLEND_FACTOR_ZERO,
        VK_BLEND_OP_ADD,
        VK_BLEND_FACTOR_ONE,
        VK_BLEND_FACTOR_ZERO,
        VK_BLEND_OP_ADD,
        VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT |
            VK_COLOR_COMPONENT_A_BIT};
    const VkPipelineColorBlendStateCreateInfo colorBlendState{
        VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO,
        nullptr,
        0u,
        VK_FALSE,
        VK_LOGIC_OP_COPY,
        1u,
        &colorBlendAttachment,
        {0, 0, 0, 0}};
    const VkPipelineRenderingCreateInfoKHR renderingCreateInfo{
        VK_STRUCTURE_TYPE_PIPELINE_RENDERING_CREATE_INFO_KHR,
        nullptr,
        0u,
        1u,
        &createInfo.outputImageFormat,
        VK_FORMAT_UNDEFINED,
        VK_FORMAT_UNDEFINED};
    const VkGraphicsPipelineCreateInfo graphicsPipelineCreateInfo{
        VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO,
        &renderingCreateInfo,
        0u,
        static_cast<std::uint32_t>(shaderStages.size()),
        shaderStages.data(),
        &vertexInputState,
        &inputAssemblyState,
        nullptr,
        &viewportState,
        &rasterizationState,
        &multisampleState,
        nullptr,
        &colorBlendState,
        nullptr,
        resources.m_pipelineLayout,
        VK_NULL_HANDLE,
        0u,
        VK_NULL_HANDLE,
        -1};
    vulkanResult =
        vkCreateGraphicsPipelines(createInfo.logicalDevice, VK_NULL_HANDLE, 1u,
                                  &graphicsPipelineCreateInfo, nullptr, &resources.m_pipeline);
    vkDestroyShaderModule(createInfo.logicalDevice, fragmentShaderModule, nullptr);
    vkDestroyShaderModule(createInfo.logicalDevice, vertexShaderModule, nullptr);
    if (vulkanResult != VK_SUCCESS) {
        return std::unexpected(vulkanResult);
    }
    return resources;
}

VulkanHostImageCompositionResources::VulkanHostImageCompositionResources(
    VulkanHostImageCompositionResources&& movedFrom) noexcept
    : m_logicalDevice(std::exchange(movedFrom.m_logicalDevice, VK_NULL_HANDLE)),
      m_extent(std::exchange(movedFrom.m_extent, VkExtent2D{})),
      m_hostImageView(std::exchange(movedFrom.m_hostImageView, VK_NULL_HANDLE)),
      m_sampler(std::exchange(movedFrom.m_sampler, VK_NULL_HANDLE)),
      m_descriptorSetLayout(std::exchange(movedFrom.m_descriptorSetLayout, VK_NULL_HANDLE)),
      m_descriptorPool(std::exchange(movedFrom.m_descriptorPool, VK_NULL_HANDLE)),
      m_descriptorSet(std::exchange(movedFrom.m_descriptorSet, VK_NULL_HANDLE)),
      m_pipelineLayout(std::exchange(movedFrom.m_pipelineLayout, VK_NULL_HANDLE)),
      m_pipeline(std::exchange(movedFrom.m_pipeline, VK_NULL_HANDLE)),
      m_beginRenderingFunction(std::exchange(movedFrom.m_beginRenderingFunction, nullptr)),
      m_endRenderingFunction(std::exchange(movedFrom.m_endRenderingFunction, nullptr)) {}

VulkanHostImageCompositionResources::~VulkanHostImageCompositionResources() {
    destroyOwnedObjects();
}

void VulkanHostImageCompositionResources::recordCommands(
    VkCommandBuffer commandBuffer, VkImageView outputImageView) const noexcept {
    const VkRenderingAttachmentInfoKHR colorAttachment{
        VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO_KHR,
        nullptr,
        outputImageView,
        VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
        VK_RESOLVE_MODE_NONE,
        VK_NULL_HANDLE,
        VK_IMAGE_LAYOUT_UNDEFINED,
        VK_ATTACHMENT_LOAD_OP_DONT_CARE,
        VK_ATTACHMENT_STORE_OP_STORE,
        {}};
    const VkRenderingInfoKHR renderingInfo{VK_STRUCTURE_TYPE_RENDERING_INFO_KHR,
                                           nullptr,
                                           0u,
                                           VkRect2D{{0, 0}, m_extent},
                                           1u,
                                           0u,
                                           1u,
                                           &colorAttachment,
                                           nullptr,
                                           nullptr};
    m_beginRenderingFunction(commandBuffer, &renderingInfo);
    vkCmdBindPipeline(commandBuffer, VK_PIPELINE_BIND_POINT_GRAPHICS, m_pipeline);
    vkCmdBindDescriptorSets(commandBuffer, VK_PIPELINE_BIND_POINT_GRAPHICS, m_pipelineLayout, 0u,
                            1u, &m_descriptorSet, 0u, nullptr);
    vkCmdDraw(commandBuffer, 3u, 1u, 0u, 0u);
    m_endRenderingFunction(commandBuffer);
}

void VulkanHostImageCompositionResources::destroyOwnedObjects() noexcept {
    if (m_logicalDevice == VK_NULL_HANDLE) {
        return;
    }
    if (m_pipeline != VK_NULL_HANDLE) {
        vkDestroyPipeline(m_logicalDevice, m_pipeline, nullptr);
    }
    if (m_pipelineLayout != VK_NULL_HANDLE) {
        vkDestroyPipelineLayout(m_logicalDevice, m_pipelineLayout, nullptr);
    }
    if (m_descriptorPool != VK_NULL_HANDLE) {
        vkDestroyDescriptorPool(m_logicalDevice, m_descriptorPool, nullptr);
    }
    if (m_descriptorSetLayout != VK_NULL_HANDLE) {
        vkDestroyDescriptorSetLayout(m_logicalDevice, m_descriptorSetLayout, nullptr);
    }
    if (m_sampler != VK_NULL_HANDLE) {
        vkDestroySampler(m_logicalDevice, m_sampler, nullptr);
    }
    if (m_hostImageView != VK_NULL_HANDLE) {
        vkDestroyImageView(m_logicalDevice, m_hostImageView, nullptr);
    }
    m_pipeline = VK_NULL_HANDLE;
    m_pipelineLayout = VK_NULL_HANDLE;
    m_descriptorSet = VK_NULL_HANDLE;
    m_descriptorPool = VK_NULL_HANDLE;
    m_descriptorSetLayout = VK_NULL_HANDLE;
    m_sampler = VK_NULL_HANDLE;
    m_hostImageView = VK_NULL_HANDLE;
    m_extent = {};
    m_beginRenderingFunction = nullptr;
    m_endRenderingFunction = nullptr;
    m_logicalDevice = VK_NULL_HANDLE;
}

} // namespace barrieww
